const topics = [
  'Future Plans',
  'Work or School Experiences',
  'Family',
  'Hobbies and Interests',
  'Travel Dreams',
  'Favorite Movies and TV Shows',
  'Personal Goals',
  'Food and Cooking',
  'Music Preferences',
  'Childhood Memories',
  'Health and Fitness',
  'Friends',
  'Relationship Expectations',
  'Favorite Books',
  'Financial Planning',
  'Technology and Gadgets',
  'Current Events',
  'Home Decorating Ideas',
  'Personal Challenges',
  'Fashion and Style',
  'Sports and Teams',
  'Pets and Animals',
  'Environmental Issues',
  'Cultural Experiences',
  'Language Learning',
  'Volunteering and Charities',
  'Photography and Art',
  'Favorite Restaurants and Cafes',
  'Dream Jobs',
  'Memories of Past Trips',
  'Gaming and Video Games',
  'Relationship Memories',
  'Education and Learning',
  'Health and Wellness Trends',
  'Personal Achievements',
  'Dreams and Aspirations',
  'Wine and Beverages',
  'Social Media Trends',
  'Political Views',
  'Psychology and Mindset',
  'Holiday Traditions',
  'Astrology and Horoscopes',
  'Self-Improvement',
  'Science and Innovations',
  'Philosophical Discussions',
  'Comedy and Humor',
  'Urban Legends and Myths',
  'DIY Projects',
  'Gardening and Nature',
  'Upcoming Events and Festivals',
  'Concerts and Live Music',
  'Historical Events',
  'Podcasts and Radio Shows',
  'Outdoor Adventures',
  'Creative Writing',
  'Space Exploration',
  'Art Exhibitions',
  'Local Attractions',
  'Craftsmanship and DIY Skills',
  'Meditation and Mindfulness',
  'Theatre and Performing Arts',
  'Cultural Differences',
  'Movie and Film Analysis',
  'Global Cuisine',
  'Personal Growth Experiences',
  'Magic and Illusion',
  'Social Justice Issues',
  'Video Production and YouTube',
  'Virtual Reality and Future Tech',
  'Local Politics',
  'Dance and Movement',
  'Strange and Unusual Facts',
  'Traditional Festivals',
  'Entrepreneurship and Startups',
  'World Literature',
  'Exotic Animals',
  'Fitness Challenges',
  'Board Games and Puzzles',
  'Sustainable Living',
  'Historical Fiction',
  'Paranormal Experiences',
  'Food Festivals',
  'Poetry and Spoken Word',
  'Extreme Sports',
  'Classic Cars and Motorcycles',
  'Astronomy and Stargazing',
  'Biographies of Influential People',
  'Wildlife Conservation',
  'Home Brewing and Mixology',
  'Antique Collection',
  'Philosophy and Ethics',
  'Fashion Design and Trends',
  'Cryptocurrency and Blockchain',
  'Photography Techniques',
  'World Travel Experiences',
  'Martial Arts and Self-Defense',
  'Classic Literature',
  'Luxury Brands and Products',
  'Graphic Novels and Comics',
  'Coffee Culture and Tasting',
  'Artificial Intelligence and Robotics',
  'Yoga and Holistic Health',
  'Stand-up Comedy Shows',
  'Religious Beliefs and Practices',
  'Surfing and Beach Culture',
  'Online Gaming Communities',
  'Language and Linguistics',
  'Public Speaking and Debate',
  'Vintage Fashion and Retro Trends',
  'Molecular Gastronomy and Food Science',
  'World History and Civilizations',
  'Mountain Climbing and Hiking',
  'Underwater Exploration and Scuba Diving',
  'International Politics and Diplomacy',
  'Urban Planning and Architecture',
  'Baking and Pastry Arts',
  'Calligraphy and Hand Lettering',
  'Forensic Science and Criminology',
  'Archaeology and Ancient Discoveries',
  'Eco-Friendly Technology',
  'Mythology and Folklore',
  'Tattoo Art and Body Modification',
  'Bird Watching and Ornithology',
  'Cycling and Bike Trails',
  'Herbalism and Natural Remedies',
  'Independent Films and Cinematography',
  'Jazz and Blues Music',
  'Neuroscience and Psychology',
  'Organic Gardening and Farming',
  'Snowboarding and Winter Sports',
  'Traditional Crafts and Handiwork',
  'Vegan and Vegetarian Lifestyles',
  'Wine Making and Viticulture',
  'Astronomy and Telescopic Observations',
  'Chess and Strategic Games',
  'Contemporary Art and Installations',
  'Desert Trekking and Survival Skills',
  'Electronic Dance Music and Festivals',
  'Fantasy and Science Fiction Literature',
  'Geocaching and Treasure Hunting',
  'Human Rights and Activism',
  'Interior Design and Feng Shui',
  'Kayaking and Water Sports',
  'Microbreweries and Craft Beer',
  'Nature Photography and Wildlife',
  'Opera and Classical Music',
  'Psychology and Mental Health',
  'Robotics and Automation',
  'Sailing and Maritime Adventures',
  'Skateboarding and Urban Sports',
  'Traditional and Fusion Cuisine',
  'Urban Exploration and Abandoned Places',
  'Virtual Learning and Online Courses',
  'Woodworking and Carpentry',
  'Acrobatics and Circus Arts',
  'Bodybuilding and Strength Training',
  'Cultural Anthropology and Societies',
  'Digital Art and Graphic Design',
  'Ethical Hacking and Cybersecurity',
  'Folk Music and Cultural Heritage',
  'Gourmet Coffee and Barista Skills',
  'Historical Reenactment and Cosplay',
  'Indie Music and Underground Scenes',
  'Knitting and Crochet Crafts',
  'Martial Arts Films and Cinema',
  'National Parks and Conservation',
  'Origami and Paper Crafts',
  'Photography and Cinematography',
  'Quantum Physics and Theories',
  'Renewable Energy and Sustainability',
  'Scuba Diving and Marine Life',
  'Tea Culture and Tasting',
  'Urban Farming and Agriculture',
  'Wildlife Photography and Conservation',
  'Animation and Cartoon Art',
  'Brazilian Jiu-Jitsu and Martial Arts',
  'Culinary Tours and Food Tasting',
  'Drone Piloting and Aerial Photography',
  'Environmental Activism and Policies',
  'Fashion Photography and Modeling',
  'Glassblowing and Sculpture',
  'Handwriting Analysis and Graphology',
  'Ice Skating and Winter Activities',
  'Juggling and Performance Arts',
  'Kite Surfing and Wind Sports',
  'Latin Dance and Music',
  'Mountain Biking and Trail Riding',
  'Nutrition and Healthy Eating',
  'Online Marketing and Branding',
  'Plant-Based Diets and Cooking',
  'Quantum Computing and Technology',
  'Rock Climbing and Bouldering',
  'Street Art and Graffiti Culture',
  'Theatre Production and Stage Design',
  'Underwater Photography and Videography',
  'Volcanology and Geological Studies',
  'World Religions and Spiritual Practices',
  'Yoga Retreats and Wellness',
  'Zumba and Dance Fitness',
  'Astrophotography and Night Sky Imaging',
]

const vals = [
  {
    name: 'Ethnicity',
    values: [ 'Caucasian', 'Asian', 'Arabic', 'Hindi', 'Latina', 'Black/afro' ]
  },
  {
    name: 'Eye Color',
    values: [ 'Brown', 'Gray', 'Blue', 'Green' ]
  },
  {
    name: 'Hair Style',
    values: [ 'Straight', 'Curly', 'Ponytail', 'Braids' ]
  },
  {
    name: 'Hair Length',
    values: [ 'Long', 'Short' ]
  },
  {
    name: 'Hair Color',
    values: [ 'Brunette', 'Blonde', 'Red', 'Pink' ]
  },
  {
    name: 'Body Type',
    values: [ 'Petite', 'Slim', 'Athletic', 'Curvy' ]
  },
  {
    name: 'Breast Size',
    values: [ 'Small', 'Medium', 'Large', 'Huge' ]
  },
  {
    name: 'Butt Size',
    values: [ 'Small', 'Medium', 'Large', 'Huge' ]
  },
  {
    name: 'Personality',
    values: [
      {
        name: 'Lover',
        description: 'Romantic, affectionate, and cherishes emotional connection.'
      },
      {
        name: 'Innocent',
        description: 'Optimistic, naive, and sees world with wonder.'
      },
      {
        name: 'Submissive',
        description: 'Obedient, yielding, and happy to follow.'
      },
      {
        name: 'Nympho',
        description: 'Insatiable, passionate, and constantly craving intimacy.'
      },
      {
        name: 'Dominant',
        description: 'Assertive, controlling, and commanding.'
      },
      {
        name: 'Mean',
        description: 'Cold, dismissive, and often sarcastic.'
      },
      {
        name: 'Adventurous',
        description: 'Daring, spontaneous, and loves new experiences.'
      },
      {
        name: 'Intellectual',
        description: 'Intelligent, thoughtful, and enjoys deep conversations.'
      },
      {
        name: 'Artistic',
        description: 'Creative, expressive, and passionate about arts.'
      },
      {
        name: 'Comedian',
        description: 'Funny, witty, and always able to make you laugh.'
      },
      {
        name: 'Empath',
        description: 'Understanding, compassionate, and emotionally attuned.'
      },
      {
        name: 'Enigmatic',
        description: 'Mysterious, intriguing, and keeps you guessing.'
      },
      {
        name: 'Fitness Enthusiast',
        description: 'Energetic, health-conscious, and loves physical activities.'
      },
      {
        name: 'Gamer',
        description: 'Playful, competitive, and loves video games.'
      },
      {
        name: 'Dreamer',
        description: 'Idealistic, imaginative, and always lost in thoughts.'
      },
      {
        name: 'Rebel',
        description: 'Independent, unconventional, and challenges norms.'
      },
      {
        name: 'Nature Lover',
        description: 'Earthy, serene, and finds peace in the natural world.'
      },
      {
        name: 'Culinary Expert',
        description: 'Gourmet, food-loving, and enjoys cooking and tasting new dishes.'
      },
      {
        name: 'Fashionista',
        description: 'Stylish, trendy, and always dressed to impress.'
      },
      {
        name: 'Bookworm',
        description: 'Literary, well-read, and loves losing herself in books.'
      },
    ]
  },
  {
    name: 'Occupation',
    values: [
      'Dentist',
      'Librarian',
      'Designer',
      'Stylist',
      'Scientist',
      'Writer',
      'Teacher',
      'Firefighter',
      'Lawyer',
      'Chef',
      'Veterinarian',
      'Software Developer',
      'Pilot',
      'Fitness Trainer',
      'Photographer',
      'Engineer',
      'Architect',
      'Nurse',
      'Diplomat',
      'Artist',
      'Physiotherapist',
      'Biologist',
      'Journalist',
      'Entrepreneur',
      'Musician',
      'Psychologist',
      'Astronaut',
      'Detective',
      'Fashion Model',
      'Marine Biologist',
      'Botanist',
      'Archaeologist',
      'Film Director',
      'Interior Designer',
      'Professional Athlete',
      'Translator',
      'Makeup Artist',
      'Animator',
      'Environmental Scientist',
      'Dancer',
      'Web Developer',
      'Graphic Designer',
      'Urban Planner',
      'Pastry Chef',
      'Art Curator',
      'Political Strategist',
      'Robotics Engineer',
      'Ethical Hacker',
      'Astronomer',
      'Flight Attendant',
      'Forensic Scientist',
      'Game Developer',
      'Aeronautical Engineer',
      'Surgeon',
      'Geologist',
      'Meteorologist',
      'Pilot',
      'Cartographer',
      'Real Estate Agent',
      'Cybersecurity Expert',
      'Fashion Designer',
      'Actor',
      'Personal Trainer',
      'Zoologist',
      'Event Planner',
      'Chiropractor',
      'Sommelier',
      'Investment Banker',
      'Oceanographer',
    ]
  },
  {
    name: 'Hobbies',
    values: [
      'Cycling',
      'Blogging',
      'Hiking',
      'Gaming',
      'Partying',
      'Photography',
      'Volunteering',
      'Cars',
      'Theater',
      'Cooking',
      'Painting',
      'Yoga',
      'Dancing',
      'Reading',
      'Gardening',
      'Music Production',
      'Knitting',
      'Surfing',
      'Traveling',
      'Skydiving',
      'Scuba Diving',
      'Martial Arts',
      'Fashion Design',
      'Baking',
      'Astronomy',
      'Pottery',
      'Film Making',
      'Wine Tasting',
      'Horseback Riding',
      'Calligraphy',
      'Bird Watching',
      'Rock Climbing',
      'Archery',
      'Skateboarding',
      'Snowboarding',
      'Stand-Up Comedy',
      'Magic Tricks',
      'Origami',
      'Podcasting',
      'Language Learning',
      'Beekeeping',
      'Chess',
      'Kite Surfing',
      'Geocaching',
      'Metalworking',
      'Digital Art',
      'Home Brewing',
      'Tarot Reading',
      'Robotics',
      'Sailing',
      'Ice Skating',
      'Candle Making',
      'Soap Making',
      'Fossil Hunting',
      'Urban Exploration',
      'Historical Reenactment',
      'Astrophotography',
      'Puppetry',
      'Parkour',
      'Sand Sculpting',
      'LARPing (Live Action Role Playing)',
      'Aquarium Keeping',
      'Cross-Stitch',
      'Wood Carving',
      'VR Gaming (Virtual Reality)',
      'Spearfishing',
      'Hot Air Ballooning',
      'Drone Racing',
      'Cosplay',
    ]
  },  
]

const names = [
  'Emma',
  'Olivia',
  'Ava',
  'Isabella',
  'Sophia',
  'Mia',
  'Charlotte',
  'Amelia',
  'Harper',
  'Evelyn',
  'Abigail',
  'Emily',
  'Elizabeth',
  'Mila',
  'Ella',
  'Avery',
  'Sofia',
  'Camila',
  'Aria',
  'Scarlett',
  'Victoria',
  'Madison',
  'Luna',
  'Grace',
  'Chloe',
  'Penelope',
  'Layla',
  'Riley',
  'Zoey',
  'Nora',
  'Lily',
  'Eleanor',
  'Hannah',
  'Lillian',
  'Addison',
  'Aubrey',
  'Ellie',
  'Stella',
  'Natalie',
  'Zoe',
  'Leah',
  'Hazel',
  'Violet',
  'Aurora',
  'Savannah',
  'Audrey',
  'Brooklyn',
  'Bella',
  'Claire',
  'Skylar',
  'Lucy',
  'Paisley',
  'Everly',
  'Anna',
  'Caroline',
  'Nova',
  'Genesis',
  'Emilia',
  'Kennedy',
  'Samantha',
  'Maya',
  'Willow',
  'Kinsley',
  'Naomi',
  'Aaliyah',
  'Elena',
  'Sarah',
  'Ariana',
  'Allison',
  'Gabriella',
  'Alice',
  'Madelyn',
  'Cora',
  'Ruby',
  'Eva',
  'Serenity',
  'Autumn',
  'Adeline',
  'Hailey',
  'Gianna',
  'Valentina',
  'Isla',
  'Eliana',
  'Quinn',
  'Nevaeh',
  'Ivy',
  'Sadie',
  'Piper',
  'Lydia',
  'Alexa',
  'Josephine',
  'Emery',
  'Julia',
  'Delilah',
  'Arianna',
  'Vivian',
  'Kaylee',
  'Sophie',
  'Brielle',
  'Madeline',
  'Peyton',
  'Rylee',
  'Clara',
  'Raelynn',
  'Melanie',
  'Mackenzie',
  'Reagan',
  'Adalynn',
  'Lilyana',
  'Catalina',
  'Alina',
  'Brynlee',
  'Elyse',
  'Finley',
  'Cadence',
  'Amiyah',
  'Rosalie',
  'Brady',
  'Esther',
  'Francesca',
  'Aspen',
  'Camille',
  'Arielle',
  'Elsie',
  'Katie',
  'Eden',
  'Annabelle',
  'Mikayla',
  'Alyssa',
  'Angela',
  'Mariah',
  'Mya',
  'Brianna',
  'Roselyn',
  'Rowan',
  'Vanessa',
  'Dakota',
  'Lilah',
  'Juliet',
  'Leila',
  'Alana',
  'Gwen',
  'Kara',
  'Elise',
  'Lacey',
  'Erin',
  'Felicity',
  'Jessica',
  'Jillian',
  'Kelsey',
  'Laurel',
  'London',
  'Mercedes',
  'Morgan',
  'Natalia',
  'Ophelia',
  'Paige',
  'Presley',
  'Remy',
  'Sienna',
  'Tara',
  'Tessa',
  'Whitney',
  'Yvette',
  'Zoie',
  'Ada',
  'Beatrice',
  'Cecelia',
  'Daisy',
  'Eleanor',
  'Frida',
  'Gemma',
  'Harper',
  'Isabelle',
  'Jada',
  'Kaitlyn',
  'Lana',
  'Mabel',
  'Nadia',
  'Olive',
  'Phoebe',
  'Queenie',
  'Raquel',
  'Sahara',
  'Tatum',
  'Uma',
  'Valeria',
  'Wendy',
  'Xena',
  'Yasmin',
  'Zara',
  'Audrina',
  'Briar',
  'Cassidy',
  'Delaney',
  'Elaina',
  'Faith',
  'Gracie',
  'Hope',
  'Imani',
]

function generateAge() {
  return Math.floor(Math.random() * (60 - 18 + 1) + 18)
}

function generateModel() {
  const model = {}
  vals.forEach(val => {
    model[val.name] = val.values[Math.floor(Math.random() * val.values.length)]
  })

  model.Personality = model.Personality.name + ' - ' + model.Personality.description

  // if(Math.random() >= 0.5)
  //   model['Hobbies'] = model['Hobbies'] + ', ' + vals[10].values[Math.floor(Math.random() * vals[10].values.length)]

  model['Age'] = generateAge()

  model['Name'] = names[Math.floor(Math.random() * names.length)]

  return model
}

function generateEntropy() {
  const model = generateModel()
  const topic = topics[Math.floor(Math.random() * topics.length)]

  return {
    model,
    topic
  }
}

module.exports = generateEntropy